version: '3'

services:
  flaskapp:
    build: .
    ports:
      - "8000:8000"
    network_mode: bridge

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=54.170.128.248
    restart: always
    network_mode: host

